apiVersion: apps/v1
kind: Deployment
metadata:
  name: dinosaur-game-deployment
spec:
  replicas: 2  # Number of desired replicas
  selector:
    matchLabels:
      app: dinosaur-game
  template:
    metadata:
      labels:
        app: dinosaur-game
    spec:
      containers:
      - name: dinosaur-game
        image: yash5090/dinosaur-game:latest
        ports:
        - containerPort: 5000
