apiVersion: apps/v1
kind: Deployment
metadata:
  name: javascript-game-deployment
spec:
  replicas: 2  # Number of desired replicas
  selector:
    matchLabels:
      app: javascript-game
  template:
    metadata:
      labels:
        app: javascript-game
    spec:
      containers:
      - name: javascript-game
        image: rameshkumarverma/javascript-game
        ports:
        - containerPort: 80
