apiVersion: apps/v1
kind: Deployment
metadata:
  name: dinosaur-deployment
spec:
  replicas: 2  # Number of desired replicas
  selector:
    matchLabels:
      app: dinosaur
  template:
    metadata:
      labels:
        app: dinosaur
    spec:
      containers:
      - name: dinosaur
        image: yash5090/dinosaur:latest
        ports:
        - containerPort: 5000
