apiVersion: apps/v1
kind: Deployment
metadata:
  name: dinosaur-deployment
spec:
  replicas: 2 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: dinosaur
  template:
    metadata:
      labels:
        app: dinosaur
    spec:
      containers:
        - name: dinosaur
          image: yash5090/dinosaur:latest # Replace with the actual image tag
          ports:
            - containerPort: 5000 # Replace with the port your Tetris game listens on
