apiVersion: apps/v1
kind: Deployment
metadata:
  name: dinosaur-game-deployment
spec:
  replicas: 2 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: dinosaur-game
  template:
    metadata:
      labels:
        app: dinosaur-game
    spec:
      containers:
        - name: dinosaur-game
          image: yash5090/dinosaur-game:latest # Replace with the actual image tag
          ports:
            - containerPort: 5000 # Replace with the port your Tetris game listens on
