apiVersion: v1
kind: Service
metadata:
  name: dinosaur-game-service
spec:
  selector:
    app: dinosaur-game
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
